import './globals.css'
import { Inter } from 'next/font/google'
import { ClerkProvider } from '@clerk/nextjs';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: "AXIS'24",
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
   
    <html lang="en">
      <body className={inter.className}>
      <ClerkProvider>
        {children}
    </ClerkProvider>
      </body>
    </html>
  )
}
