
import './globals.css'
import { Inter } from 'next/font/google'
import { NextAuthProvider } from "./providers";
const inter = Inter({ subsets: ['latin'] })
import { toast, ToastContainer } from "react-toastify";
import StyledComponentsRegistry from './registry'
import "react-toastify/dist/ReactToastify.css";
export const metadata = {
  title: "AXIS'24",
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <ToastContainer/>
 
<NextAuthProvider> {children}
</NextAuthProvider>

       
      

      </body>
    </html>
  )
}
